version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python3 manage.py migrate && gunicorn iioy.wsgi:application -b :8000"
    environment:
      DEBUG: 'true'
      DATABASE_URL: 'psql://postgres@db:5432/postgres'
      TMDB_API_KEY: "${TMDB_API_KEY}"
      OMDB_API_KEY: "${OMDB_API_KEY}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
    ports:
      - "8000:8000"
    depends_on:
      - db
