# Generated by Django 2.0.4 on 2018-04-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture_url',
            field=models.URLField(null=True),
        ),
    ]
